import { useState, useRef, useEffect } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useParams, useLocation } from "wouter";
import { apiClient, formatINR, formatDate } from "@/lib/api";
import { ArrowLeft, FileText, Share2, Download, MessageCircle, Mail, Smartphone, FileDown, Loader2, Printer, Edit2 } from "lucide-react";
import { generateInvoicePDF, generateInvoicePDFBlob } from "@/lib/invoicePDF";

// ============================================================================
// SHARE MENU
// ============================================================================

function ShareMenu({ bill, customerName, customerPhone, customerEmail }) {
  const [open, setOpen] = useState(false);
  const [sharing, setSharing] = useState(false);
  const ref = useRef(null);

  useEffect(() => {
    const handler = (e) => {
      if (ref.current && !ref.current.contains(e.target)) setOpen(false);
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, []);

  // Build detailed invoice message
  const buildInvoiceMessage = () => {
    const items = bill.items || [];
    const total = formatINR(bill.totalAmount);
    const paid = formatINR(bill.paidAmount || 0);
    const status = bill.status === "paid" ? "✅ PAID" : bill.status === "partial" ? "⚠️ PARTIAL PAID" : "🔴 UNPAID";

    let msg = `📄 *INVOICE*\n`;
    msg += `━━━━━━━━━━━━━━━━━━\n`;
    msg += `*Invoice #:* ${bill.billNumber}\n`;
    msg += `*Invoice Code:* ${bill.billCode || "N/A"}\n`;
    msg += `*Date:* ${formatDate(bill.createdAt)}\n`;
    msg += `*Customer:* ${customerName}\n`;
    msg += `*Status:* ${status}\n`;
    msg += `━━━━━━━━━━━━━━━━━━\n\n`;

    if (items.length > 0) {
      msg += `📦 *Items:*\n`;
      items.forEach((item, i) => {
        const qty = Number(item.quantity) || 0;
        const price = formatINR(item.unitPrice);
        msg += `${i + 1}. ${item.itemName} × ${qty} — ${price}\n`;
      });
      msg += `\n`;
    }

    msg += `━━━━━━━━━━━━━━━━━━\n`;
    msg += `💰 *Total Amount:* ${total}\n`;
    msg += `✅ *Paid:* ${paid}\n`;
    if (bill.status !== "paid") {
      const due = Number(bill.totalAmount || 0) - Number(bill.paidAmount || 0);
      msg += `⚠️ *Balance Due:* ${formatINR(due)}\n`;
    }
    msg += `━━━━━━━━━━━━━━━━━━\n\n`;
    msg += `🙏 *Thank you for your business!*\n`;
    msg += `We truly appreciate your trust in us. For any queries regarding this invoice, please don't hesitate to reach out.\n\n`;
    msg += `_Generated by VyaparBook_`;

    return msg;
  };

  // Helper: get full bill data and generate PDF file
  const getBillAndPDF = async () => {
    let fullBill;
    try {
      fullBill = await apiClient.getBill(bill.id);
    } catch {
      fullBill = { ...bill, customer: { name: customerName, phone: customerPhone, email: customerEmail } };
    }
    const pdfFile = await generateInvoicePDFBlob(fullBill);
    return pdfFile;
  };

  const shareWhatsApp = async (e) => {
    e.stopPropagation();
    setSharing(true);
    try {
      const pdfFile = await getBillAndPDF();
      const msg = buildInvoiceMessage();

      // Try Web Share API with file (works on mobile & modern browsers)
      if (navigator.canShare && navigator.canShare({ files: [pdfFile] })) {
        await navigator.share({
          title: `Invoice ${bill.billNumber}`,
          text: msg,
          files: [pdfFile],
        });
      } else {
        // Fallback: auto-download PDF + open WhatsApp with text
        const url = URL.createObjectURL(pdfFile);
        const a = document.createElement("a"); a.href = url; a.download = pdfFile.name; a.click();
        URL.revokeObjectURL(url);

        const phone = customerPhone ? customerPhone.replace(/[^0-9]/g, "") : "";
        const waUrl = phone
          ? `https://wa.me/${phone.startsWith("91") ? phone : "91" + phone}?text=${encodeURIComponent(msg)}`
          : `https://wa.me/?text=${encodeURIComponent(msg)}`;
        window.open(waUrl, "_blank");
      }
    } catch (err) {
      if (err.name !== "AbortError") console.error("Share failed:", err);
    } finally {
      setSharing(false);
      setOpen(false);
    }
  };

  const shareEmail = async (e) => {
    e.stopPropagation();
    setSharing(true);
    try {
      const pdfFile = await getBillAndPDF();
      const body = buildInvoiceMessage().replace(/\*/g, "");
      const subject = `Invoice ${bill.billNumber} - ${formatINR(bill.totalAmount)} | VyaparBook`;

      // Try Web Share API with file
      if (navigator.canShare && navigator.canShare({ files: [pdfFile] })) {
        await navigator.share({
          title: subject,
          text: body,
          files: [pdfFile],
        });
      } else {
        // Fallback: auto-download PDF + open mailto
        const url = URL.createObjectURL(pdfFile);
        const a = document.createElement("a"); a.href = url; a.download = pdfFile.name; a.click();
        URL.revokeObjectURL(url);

        const to = customerEmail || "";
        window.open(`mailto:${to}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`, "_blank");
      }
    } catch (err) {
      if (err.name !== "AbortError") console.error("Share failed:", err);
    } finally {
      setSharing(false);
      setOpen(false);
    }
  };

  const shareSMS = (e) => {
    e.stopPropagation();
    const phone = customerPhone ? customerPhone.replace(/[^0-9]/g, "") : "";
    const smsMsg = `Invoice ${bill.billNumber} | Amount: ${formatINR(bill.totalAmount)} | Status: ${bill.status} | Code: ${bill.billCode || "N/A"}\n\nThank you for your business! - VyaparBook`;
    window.open(`sms:${phone}?body=${encodeURIComponent(smsMsg)}`, "_blank");
    setOpen(false);
  };

  const downloadPDF = async (e) => {
    e.stopPropagation();
    setSharing(true);
    try {
      const pdfFile = await getBillAndPDF();
      const url = URL.createObjectURL(pdfFile);
      const a = document.createElement("a"); a.href = url; a.download = pdfFile.name; a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      // Fallback to preview
      apiClient.getBill(bill.id).then(fb => generateInvoicePDF(fb)).catch(() => generateInvoicePDF(bill));
    } finally {
      setSharing(false);
      setOpen(false);
    }
  };

  const printPDF = async (e) => {
    e.stopPropagation();
    setSharing(true);
    try {
      let fullBill;
      try {
        fullBill = await apiClient.getBill(bill.id);
      } catch {
        fullBill = { ...bill, customer: { name: customerName, phone: customerPhone, email: customerEmail } };
      }
      generateInvoicePDF(fullBill, { autoPrint: true });
    } finally {
      setSharing(false);
      setOpen(false);
    }
  };

  const actions = [
    { label: "WhatsApp", icon: MessageCircle, onClick: shareWhatsApp, color: "text-green-600 hover:bg-green-50" },
    { label: "Email", icon: Mail, onClick: shareEmail, color: "text-blue-600 hover:bg-blue-50" },
    { label: "SMS", icon: Smartphone, onClick: shareSMS, color: "text-purple-600 hover:bg-purple-50" },
    { label: "PDF Invoice", icon: FileDown, onClick: downloadPDF, color: "text-red-600 hover:bg-red-50" },
    { label: "Print", icon: Printer, onClick: printPDF, color: "text-orange-600 hover:bg-orange-50" },
  ];

  return (
    <div className="relative" ref={ref}>
      <button
        type="button"
        className={`p-1.5 rounded-lg transition-colors ${open ? "bg-blue-50 text-blue-600" : "text-gray-400 hover:text-gray-600 hover:bg-gray-100"}`}
        onClick={(e) => { e.stopPropagation(); setOpen(!open); }}
        title="Share bill"
        disabled={sharing}
      >
        {sharing ? <Loader2 className="w-4 h-4 animate-spin text-blue-500" /> : <Share2 className="w-4 h-4" />}
      </button>

      {open && (
        <div className="absolute right-0 top-full mt-1 z-30 bg-white border border-gray-200 rounded-xl shadow-lg py-1 w-40">
          {actions.map(({ label, icon: Icon, onClick, color }) => (
            <button
              key={label}
              type="button"
              className={`w-full flex items-center gap-2.5 px-3 py-2 text-sm font-medium transition-colors ${color}`}
              onClick={onClick}
              disabled={sharing}
            >
              <Icon className="w-4 h-4" />
              {label}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

// ============================================================================
// CUSTOMER DETAIL
// ============================================================================

export default function CustomerDetail() {
  const { id } = useParams();
  const [, navigate] = useLocation();
  const qc = useQueryClient();

  const { data: customer, isLoading } = useQuery({
    queryKey: ["customer", id],
    queryFn: () => apiClient.getCustomer(id),
  });
  const { data: bills = [] } = useQuery({
    queryKey: ["bills", { customerId: id }],
    queryFn: async () => {
      const response = await apiClient.getBills({ customerId: id });
      return response.data || response.bills || response || [];
    }
  });

  const updateMutation = useMutation({
    mutationFn: (data) => apiClient.updateCustomer(id, data),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["customer", id] }),
  });

  if (isLoading) return <p className="text-center py-20 text-gray-400">Loading…</p>;
  if (!customer) return <p className="text-center py-20 text-red-500">Customer not found.</p>;

  const outstanding = Number(customer.totalBilled || 0) - Number(customer.totalPaid || 0);

  return (
    <div className="space-y-6 max-w-4xl">
      <div className="flex items-center gap-3">
        <button className="btn btn-ghost p-2" onClick={() => navigate("/customers")}>
          <ArrowLeft className="w-4 h-4" />
        </button>
        <div className="flex-1">
          <h1 className="text-2xl font-bold text-gray-900">{customer.name}</h1>
          <p className="text-sm text-gray-500">{customer.phone} {customer.email ? `· ${customer.email}` : ""}</p>
        </div>
        <button className="btn btn-outline gap-2" onClick={() => navigate(`/customers/${customer.id}/edit`)}>
          <Edit2 className="w-4 h-4" /> Edit Profile
        </button>
      </div>

      {/* Balance Cards */}
      <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
        {[
          { label: "Total Billed", value: formatINR(customer.totalBilled), color: "text-gray-900" },
          { label: "Total Paid", value: formatINR(customer.totalPaid), color: "text-emerald-600" },
          { label: "Outstanding", value: formatINR(outstanding), color: outstanding > 0 ? "text-red-600" : "text-gray-400" },
        ].map(c => (
          <div key={c.label} className="card p-4">
            <p className="text-xs text-gray-500 mb-1">{c.label}</p>
            <p className={`text-xl font-bold ${c.color}`}>{c.value}</p>
          </div>
        ))}
      </div>

      {/* Details */}
      <div className="card p-5">
        <h2 className="font-semibold text-gray-900 mb-4">Customer Details</h2>
        <dl className="grid grid-cols-2 md:grid-cols-4 gap-6 text-sm">
          {[
            { label: "Email Address", value: customer.email },
            { label: "GST Number", value: customer.gstNumber },
            { label: "PAN Number", value: customer.panNumber },
            { label: "Pincode", value: customer.pincode },
            { label: "Last Purchase", value: customer.lastPurchaseDate ? formatDate(customer.lastPurchaseDate) : "No purchases" },
            { label: "Total Visits", value: customer.billCount ? `${customer.billCount} Times` : "0 Times" },
            { label: "Lifetime Profit", value: formatINR(customer.totalProfit || 0), color: "text-emerald-600 font-bold" },
            { label: "Customer Joined", value: formatDate(customer.createdAt) },
          ].map(({ label, value, color }) => (
            <div key={label}>
              <dt className="text-gray-500 text-[10px] font-bold uppercase tracking-wider mb-0.5">{label}</dt>
              <dd className={`font-semibold text-gray-900 ${color || ""}`}>{value || "—"}</dd>
            </div>
          ))}
        </dl>
        <div className="mt-6 pt-6 border-t border-gray-100">
          <dt className="text-gray-500 text-[10px] font-bold uppercase tracking-wider mb-1">Billing Address</dt>
          <dd className="text-gray-900 font-medium">{customer.address || "No address provided"}</dd>
        </div>
      </div>

      {/* Bills */}
      <div className="card p-5">
        <h2 className="font-semibold text-gray-900 mb-4 flex items-center gap-2">
          <FileText className="w-4 h-4 text-blue-600" /> Bills ({bills.length})
        </h2>
        {bills.length === 0 ? (
          <p className="text-sm text-gray-400">No bills yet.</p>
        ) : (
          <table className="w-full text-sm">
            <thead className="border-b">
              <tr className="text-left text-xs text-gray-500">
                <th className="pb-2">Bill #</th>
                <th className="pb-2">Invoice No.</th>
                <th className="pb-2">Date</th>
                <th className="pb-2">Status</th>
                <th className="pb-2 text-right">Amount</th>
                <th className="pb-2 w-12 text-center">Share</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {bills.map(b => (
                <tr key={b.id} className="hover:bg-gray-50 cursor-pointer" onClick={() => navigate(`/bills/${b.id}`)}>
                  <td className="py-2.5 font-medium text-blue-600">{b.billNumber}</td>
                  <td className="py-2.5">
                    {b.billCode ? (
                      <span className="font-mono text-xs font-semibold tracking-wider bg-amber-50 text-amber-700 border border-amber-200 px-1.5 py-0.5 rounded-md">
                        {b.billCode}
                      </span>
                    ) : "—"}
                  </td>
                  <td className="py-2.5 text-gray-900 font-medium">
                    {b.customerName?.toLowerCase().includes("walk-in") 
                      ? `Walk-in #${b.billCode || "N/A"}` 
                      : (b.customerName || "Walk-in")
                    }
                  </td>
                  <td className="py-2.5 text-gray-500">{formatDate(b.createdAt)}</td>
                  <td className="py-2.5">
                    <span className={`badge ${b.status === "paid" ? "badge-green" : b.status === "unpaid" ? "badge-red" : "badge-gray"}`}>
                      {b.status}
                    </span>
                  </td>
                  <td className="py-2.5 text-right font-semibold">{formatINR(b.totalAmount)}</td>
                  <td className="py-2.5 text-center">
                    <ShareMenu
                      bill={b}
                      customerName={customer.name}
                      customerPhone={customer.phone}
                      customerEmail={customer.email}
                    />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}
